name: Build BAT to EXE

on:
  push:
    branches: [ main ]
    paths:
      - 'SEE/*.bat'
      - 'Local/*.bat'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Download Bat To Exe Converter
      run: |
        Invoke-WebRequest -Uri "https://github.com/tokyoneon/B2E/raw/master/bat_to_exe_converter.zip" -OutFile "bat_to_exe_converter.zip"
        Expand-Archive -Path "bat_to_exe_converter.zip" -DestinationPath "."
        Move-Item -Path "Bat_To_Exe_Converter\Bat_To_Exe_Converter.exe" -Destination "BatToExeConverter.exe"
        Remove-Item -Path "bat_to_exe_converter.zip" -Force
        Remove-Item -Path "Bat_To_Exe_Converter" -Recurse -Force
    
    - name: Convert SEE\start.bat to EXE with Banner.png
      run: |
        .\BatToExeConverter.exe /bat SEE\start.bat /exe SEE\start.exe /icon Local\Banner.png /invisible
    
    - name: Convert Local\restore.bat to EXE with Origin.png
      run: |
        .\BatToExeConverter.exe /bat Local\restore.bat /exe Local\restore.exe /icon Local\Origin.png /invisible
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: exe-files
        path: |
          SEE\start.exe
          Local\restore.exe
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.run_number }}
        name: Release v${{ github.run_number }}
        files: |
          SEE\start.exe
          Local\restore.exe